QuizApp/Controllers/optionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp;

namespace QuizApp.Controllers
{
    public class optionsController : Controller
    {
        private quiz_webappEntities db = new quiz_webappEntities();

        // GET: options
        public ActionResult Index()
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            var options = db.options.Include(o => o.question).Where(d=>d.question.isactive==true);
            return View(options.ToList());
        }

        // GET: options/Details/5
        public ActionResult Details(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            option option = db.options.Find(id);
            if (option == null)
            {
                return HttpNotFound();
            }
            return View(option);
        }

        // GET: options/Create
        public ActionResult Create()
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.question_id = new SelectList(db.questions, "id", "question1");
            return View();
        }

        // POST: options/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,question_id,choice_text,iscorrect")] option option)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.options.Add(option);
                db.SaveChanges();
                
                return RedirectToAction("Create");
            }

            ViewBag.question_id = new SelectList(db.questions, "id", "question1", option.question_id);
            return View(option);
        }

        // GET: options/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            option option = db.options.Find(id);
            if (option == null)
            {
                return HttpNotFound();
            }
            ViewBag.question_id = new SelectList(db.questions, "id", "question1", option.question_id);
            return View(option);
        }

        // POST: options/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,question_id,choice_text,iscorrect")] option option)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(option).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.question_id = new SelectList(db.questions, "id", "question1", option.question_id);
            return View(option);
        }

        // GET: options/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            option option = db.options.Find(id);
            if (option == null)
            {
                return HttpNotFound();
            }
            return View(option);
        }

        // POST: options/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            option option = db.options.Find(id);
            db.options.Remove(option);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuizApp/Controllers/questionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizApp;

namespace QuizApp.Controllers
{
    public class questionsController : Controller
    {
        private quiz_webappEntities db = new quiz_webappEntities();

        // GET: questions
        public ActionResult Index()
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            var questions = db.questions.Include(q => q.question_type);
            return View(questions.Where(d => d.isactive == true).ToList());
        }

        // GET: questions/Details/5
        public ActionResult Details(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: questions/Create
        public ActionResult Create()
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.question_type_id = new SelectList(db.question_type, "id", "name");
            return View();
        }

        // POST: questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,question1,isactive,difficulty_level,question_type_id,points,negative_points")] question question)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("../Options/Create");
            }

            ViewBag.question_type_id = new SelectList(db.question_type, "id", "name", question.question_type_id);
            return View(question);
        }

        // GET: questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.question_type_id = new SelectList(db.question_type, "id", "name", question.question_type_id);
            return View(question);
        }

        // POST: questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,question1,isactive,difficulty_level,question_type_id,points,negative_points")] question question)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.question_type_id = new SelectList(db.question_type, "id", "name", question.question_type_id);
            return View(question);
        }

        // GET: questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            question question = db.questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Helper.isAdmin == false)
            {
                return RedirectToAction("Login", "Home");
            }
            question question = db.questions.Find(id);
            question.isactive = false;
            db.Entry(question).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuizApp/Views/Options/Create.cshtml
@model QuizApp.option

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>option</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.question_id, "question_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("question_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.question_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.choice_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.choice_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.choice_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iscorrect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.iscorrect)
                    @Html.ValidationMessageFor(model => model.iscorrect, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Options", "Index")
</div>

QuizApp/Views/Options/Delete.cshtml
@model QuizApp.option

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>option</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.choice_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.choice_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iscorrect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iscorrect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question.question1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question.question1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuizApp/Views/Options/Details.cshtml
@model QuizApp.option

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>option</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.choice_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.choice_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iscorrect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iscorrect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.question.question1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question.question1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QuizApp/Views/Options/Edit.cshtml
@model QuizApp.option

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>option</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.question_id, "question_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("question_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.question_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.choice_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.choice_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.choice_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iscorrect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.iscorrect)
                    @Html.ValidationMessageFor(model => model.iscorrect, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QuizApp/Views/Options/Index.cshtml
@model IEnumerable<QuizApp.option>

@{
    ViewBag.Title = "Index";
}

<h2>Options</h2>

<p>
    @Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("Questions", "Index", "questions")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.choice_text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iscorrect)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.question.question1)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.choice_text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.iscorrect)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.question.question1)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>